from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.map_mode = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.map_mode.setFont(font)
        self.map_mode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.map_mode.setObjectName("map_mode")
        self.map_mode.addItem("")
        self.map_mode.addItem("")
        self.map_mode.addItem("")
        self.horizontalLayout.addWidget(self.map_mode)
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset.setFont(font)
        self.reset.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reset.setObjectName("reset")
        self.horizontalLayout.addWidget(self.reset)
        self.search_line = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line.setFont(font)
        self.search_line.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_line.setObjectName("search_line")
        self.horizontalLayout.addWidget(self.search_line)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setFont(font)
        self.search_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_label.sizePolicy().hasHeightForWidth())
        self.map_label.setSizePolicy(sizePolicy)
        self.map_label.setText("")
        self.map_label.setObjectName("map_label")
        self.verticalLayout.addWidget(self.map_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.address = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address.sizePolicy().hasHeightForWidth())
        self.address.setSizePolicy(sizePolicy)
        self.address.setObjectName("address")
        self.horizontalLayout_2.addWidget(self.address)
        self.pochta_index = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pochta_index.sizePolicy().hasHeightForWidth())
        self.pochta_index.setSizePolicy(sizePolicy)
        self.pochta_index.setObjectName("pochta_index")
        self.horizontalLayout_2.addWidget(self.pochta_index)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.address.setFont(font)
        self.pochta_index.setFont(font)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "map"))
        self.map_mode.setItemText(0, _translate("MainWindow", "Схема"))
        self.map_mode.setItemText(1, _translate("MainWindow", "Гибрид"))
        self.map_mode.setItemText(2, _translate("MainWindow", "Спутник"))
        self.reset.setText(_translate("MainWindow", "Сброс поискового результата"))
        self.search_button.setText(_translate("MainWindow", "Найти"))
        self.map_label.setText(_translate("MainWindow", ""))
        self.pochta_index.setText(_translate("MainWindow", "Индекс"))
